startups/urls.py
from django.conf.urls import patterns, include, url
from startups import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    #url(r'^upvote/$', views.upvote, name='upvote'),
    #url(r'^downvote/$', views.downvote, name='downvote'),
    url(r'^add_comment/$', views.add_comment, name='add_comment'),
    url(r'^vote/$', views.vote, name='vote'),
)

startupsite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'startupsite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^startups/', include('startups.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        { 'document_root': settings.MEDIA_ROOT }), )

startups/models.py
from django.db import models

class StartupDetails(models.Model):
  name = models.CharField(max_length=30)
  short_desc = models.CharField(max_length=100)
  votes = models.IntegerField(default=0)
  funding_amount = models.IntegerField(default=0)
  logo = models.ImageField(upload_to='startup_logos',blank=True)

  def __unicode__(self):
    return self.name

class Comment(models.Model):
  name = models.CharField(max_length=30)
  text = models.CharField(max_length=100)
  startup = models.ForeignKey(StartupDetails)
  created_on = models.DateTimeField(auto_now_add=True)
  
  class Meta:
    get_latest_by = "created_on"
  
  def __unicode__(self):
    return self.text

startups/views.py
from django.shortcuts import render_to_response
from startups.models import StartupDetails, Comment
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect


def vote(request):
    startup_id = request.GET['startup_id']
    startup = StartupDetails.objects.get(id=startup_id)
    vote = int(request.GET['vote'])
    if startup_id in request.session:
        startup.votes -= request.session[startup_id]
        startup.votes += vote
        startup.save()
        request.session[startup_id] = vote
    return HttpResponse(startup.votes)


def index(request):
  context = RequestContext(request)
  startups_list = StartupDetails.objects.all().order_by('-votes')
  for startup in startups_list:
    if startup.id in request.session:
      startup.current_user_vote = request.session[startup.id]
    else:
      request.session[startup.id] = 0
      startup.current_user_vote = request.session[startup.id]

  return render_to_response('startups/index.html', {'startups_list': startups_list}, context)


def add_comment(request):
  context = RequestContext(request)
  startup_id = None
  if request.method == 'POST':
    name = request.POST['name']
    comment = request.POST['comment']
    startup_id = request.POST['startupid']
    if startup_id:
      s = StartupDetails.objects.get(pk=int(startup_id))
      c = Comment(name=name,text=comment,startup=s)
      c.save()
  return HttpResponseRedirect("/startups/")

templates/startups/index.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>League Tables: Vote for your favorite startup</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'fontawesome/css/font-awesome.min.css' %}">
<script type="text/javascript" src="{% static 'jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
</head>
<body>
<div class="container" id="refreshdiv">
<h1>League Tables: Vote for your favorite startup</h1>
<hr><br><br>
{% if messages %}
<div class="alert alert-warning">
  {% for message in messages %}
    <strong>{{ message }}</strong>
  {% endfor %}
</div>
{% endif %}

<ul class="list-group" id="autorefresh">
{% for s in startups_list %}
  <li class="list-group-item">
  <p class="lead">
  <span class="label label-warning"><b class="vote_count" id="vote_{{ s.id }}">{{ s.votes }}</b></span>&nbsp;&nbsp;
  <img src="/media/{{ s.logo }}" class="img-rounded" width=50px height=100%>&nbsp;<strong>{{ s.name }}</strong>: {{ s.short_desc }}
  
  <span class="pull-right">
  <span class="label label-danger"><strong>{{ s.funding_amount|intword }}</strong></span>&nbsp;
  {% if s.current_user_vote == 1 %}
    <a class ="upvotes" id = "{{ s.id }}" data-catid="{{ s.id }}"><i id="tup{{ s.id }}" class="fa fa-thumbs-up fa-2x" data-toggle="modal" data-target="#mymodal" ></i></a>&nbsp;
    <a class ="downvotes" id = "{{ s.id }}" data-catid="{{ s.id }}" ><i id="tdown{{ s.id }}" class="fa fa-thumbs-o-down fa-2x" data-toggle="modal" data-target="#mymodal" ></i></a>
  {% elif s.current_user_vote == -1 %}
    <a class ="upvotes" id = "{{ s.id }}" data-catid="{{ s.id }}" ><i id="tup{{ s.id }}" class="fa fa-thumbs-o-up fa-2x" data-toggle="modal" data-target="#mymodal" ></i></a>&nbsp;
    <a class ="downvotes" id = "{{ s.id }}" data-catid="{{ s.id }}"><i id="tdown{{ s.id }}" class="fa fa-thumbs-down fa-2x" data-toggle="modal" data-target="#mymodal" ></i></a>
  {% else %}
    <a class ="upvotes" id = "{{ s.id }}" data-catid="{{ s.id }}" ><i id="tup{{ s.id }}" class="fa fa-thumbs-o-up fa-2x" data-toggle="modal" data-target="#mymodal" ></i></a>&nbsp;
    <a class ="downvotes" id = "{{ s.id }}" data-catid="{{ s.id }}" ><i id="tdown{{ s.id }}" class="fa fa-thumbs-o-down fa-2x" data-toggle="modal" data-target="#mymodal" ></i></a>
  {% endif %}
  </span>
  </p>
    <div class="panel-group" id="accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <p>"{{ s.comment_set.latest }}"<a data-toggle="collapse" data-parent="#accordion" href="#" class="comments-accordion pull-right" data-catid="{{ s.id }}">More</a></p>
        </div>
        <div id="collapse{{ s.id }}" class="panel-collapse collapse in">
          <div class="panel-body">
            {% for c in s.comment_set.all %}
            {{ c.text }} <span class="pull-right"><span class="label label-info">By {{ c.name }} -- {{ c.created_on|naturaltime }}</span></span>
            <hr>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </li>
{% endfor %}
</ul>
</div>
<!-- MODAL FOR COMMENTS -->
<div id="mymodal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header"><h4>Tell us what you think</h4></div>
      <div class="modal-body">
      <form class="form" role="form" method="post" action="/startups/add_comment/">
        {% csrf_token %}

          <div class="form-group">
            <input type="hidden" class="form-control" value="" name="startupid" id="dataforcomment">
            <input type="text" class="form-control" placeholder="Name" name="name">
          </div>
          <div class="form-group">
            <textarea rows="3" class="form-control" placeholder="Comment" name="comment"></textarea>
          </div>
          <div class="form-group">
            <button class="btn btn-info btn-block comment-submit" id="postcomment{{ s.id }}">Post</button>
          </div>

      </form>
      </div>
    </div>
  </div>
</div>
<!-- END OF MODAL -->
<script type="text/javascript">
$(document).ready(function(){
  $('.collapse').collapse();
});

$('.upvotes').click(function(){
  var sid;
  sid = $(this).attr("data-catid");
  var tempid = "#vote_".concat(sid);
  var tup = "#tup".concat(sid);
  var tdown = "#tdown".concat(sid);
    $.get('/startups/vote/', {startup_id: sid, vote:1}, function(data){
      $(tempid).html(data);
    });
    $(tup).attr('class', 'fa fa-thumbs-up fa-2x');
    $(tdown).attr('class', 'fa fa-thumbs-o-down fa-2x');
    $('#dataforcomment').attr('value',sid);
    /*$.get('/startups/ #refreshdiv', function(data){
      $('#refreshdiv').empty().append(data);
    });*/
});

$('.downvotes').click(function(){
  var sid;
  sid = $(this).attr("data-catid");
  var tempid = "#vote_".concat(sid);
  var tdown = "#tdown".concat(sid);
  var tup = "#tup".concat(sid);
    $.get('/startups/vote/', {startup_id: sid, vote:-1}, function(data){
      $(tempid).html(data);
    });
    $(tdown).attr('class', 'fa fa-thumbs-down fa-2x');
    $(tup).attr('class', 'fa fa-thumbs-o-up fa-2x');
    $('#dataforcomment').attr('value',sid);
    /*$.get('/startups/ #refreshdiv', function(data){
      $('#refreshdiv').empty().append(data);
    });*/
});

$('.comments-accordion').click(function(){
  var sid = $(this).attr("data-catid");
  var tempid = "#collapse".concat(sid);
  $(tempid).collapse('toggle');
});
</script>
</body>
</html>